# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'douMiApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for douMiApp
pod 'MJRefresh'
pod 'MJExtension'
pod 'AFNetworking'
pod 'SDWebImage'
pod 'IQKeyboardManager'
pod 'Masonry'
pod 'FDFullscreenPopGesture', '~> 1.1'
pod 'CYLTabBarController', '~> 1.11.0
pod 'MBProgressHUD', '~> 1.0.0'
pod 'ZFPlayer'
pod ‘UMengUShare/UI’
pod ‘UMengUShare/Social/Sina'
pod ‘UMengUShare/Social/WeChat'
pod ‘UMengUShare/Social/QQ'
pod ‘UMengUShare/Social/SMS'
pod 'YYCache'
pod 'UMengAnalytics-NO-IDFA'
  target 'douMiAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'douMiAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
